# FROM ubuntu:16.04
# RUN apt-get update && \
#     apt install curl -y && \
#     apt install ruby -y && \
#     apt install python -y && \
#     apt install build-essential -y && \
#     apt install apache2 -y

FROM alpine
RUN apk update && \
    apk add  curl && \
    apk add  ruby && \
    apk add  python && \
    apk add  build-base && \
    apk add  apache2 


